name: 'Start IPFS Daemon'
description: 'Start IPFS daemon and wait for it to become ready'
inputs:
  args:
    description: 'Arguments that should be passed to the ipfs daemon command'
    required: false
    default: '--init --init-profile server'
  wait-for-addrs:
    description: 'Whether waits for addresses to be assigned to the daemon(defaults to true)'
    required: false
    default: true
runs:
  using: 'composite'
  steps:
    - if: ${{ runner.os == 'Linux' }}
      run: |
        sudo sysctl -w net.core.rmem_max=2500000
      shell: bash
    - run: |
        ( ipfs daemon ${{ inputs.args }} & ) | sed '/Daemon is ready/q'
      shell: bash
    - if: ${{ inputs.wait-for-addrs == 'true' }}
      run: |
        while [[ "$(ipfs id | jq '.Addresses | length')" == '0' ]]; do sleep 1; done
      shell: bash
