name: Test Build
on: [push]
jobs:
  Use-Action:
    name: Use Action
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          path: start-ipfs-daemon-action
      - uses: actions/setup-go@v4
        with:
          go-version: 'oldstable'
      - run: go install github.com/ipfs/kubo/cmd/ipfs@latest
        shell: bash
      - uses: ./start-ipfs-daemon-action
