name: Test Download
on: [push]
jobs:
  Use-Action:
    name: Use Action
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          path: start-ipfs-daemon-action
      - uses: ipfs/download-ipfs-distribution-action@v1
      - uses: ./start-ipfs-daemon-action
